name: Purchase Order
description: DO NOT USE YET- Request item(s) to be ordered!
title: "[PO]: "
labels: ["Purchasing"]
type: "Task"
projects: ["precision-sustainable-ag/5"]
assignees: kldriver
body:
  - type: markdown
    attributes:
      value: |
        "Please fill out this form as accurately and completely as possible to ensure a fast and smooth process getting your order processed."
  - type: dropdown
    id: PB
    attributes:
      label: Is this tracked in PartsBox?
      options:
        - "I don't know"
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: input
    id: project
    attributes:
      label: What project is this for?
      placeholder: "PM3D, BenchBot, ect."
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link to Order
      placeholder: "Link to PartsBox order or purchase list"
    validations:
      required: true
  - type: input
    id: cost
    attributes:
      label: Estimated Total Cost
      placeholder: "Ex: $1,250"
    validations:
      required: true
  - type: textarea
    id: ifo
    attributes:
      label: Extra info
      placeholder: "Please include any extra information we should know about this purchase. Do we need a quote? Is there a long lead time? Do CAD files or drawings need to be sent to the vendor?"
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I read and filled out every part of this forum
          required: true
